In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
oscar=pd.read_csv("oscar.csv")
oscar.head()

Film  Year  Award  Nomination
0  Everything Everywhere All at Once  2022      7          11
1     All Quiet on the Western Front  2022      4           9
2                          The Whale  2022      2           3
3                  Top Gun: Maverick  2022      1           6
4     Black Panther: Wakanda Forever  2022      1           5

In [20]:
oscar.isna().sum()

Film          1
Year          0
Award         0
Nomination    0
dtype: int64

In [21]:
oscar.dropna(inplace=True)

In [22]:
oscar.isna().sum()

Film          0
Year          0
Award         0
Nomination    0
dtype: int64

In [23]:
x=oscar.drop("Award",axis=1)
y=oscar["Award"]
x.head()


Film  Year  Nomination
0  Everything Everywhere All at Once  2022          11
1     All Quiet on the Western Front  2022           9
2                          The Whale  2022           3
3                  Top Gun: Maverick  2022           6
4     Black Panther: Wakanda Forever  2022           5

In [24]:
y.head

<bound method NDFrame.head of 0       7
1       4
2       2
3       1
4       1
       ..
1355    1
1356    2
1357    1
1358    2
1359    3
Name: Award, Length: 1359, dtype: int64>

In [53]:
x=pd.get_dummies(x['Film'])
x

12 Years a Slave  1917  20 Feet from Stardom  \
0                    0     0                     0   
1                    0     0                     0   
2                    0     0                     0   
3                    0     0                     0   
4                    0     0                     0   
...                ...   ...                   ...   
1355                 0     0                     0   
1356                 0     0                     0   
1357                 0     0                     0   
1358                 0     0                     0   
1359                 0     0                     0   

      20,000 Leagues Under the Sea  2001: A Space Odyssey  7 Faces of Dr. Lao  \
0                                0                      0                   0   
1                                0                      0                   0   
2                                0                      0                   0   
3                                0                      0                   0   
4                                0                      0                   0   
...                            ...                    ...                 ...   
1355                             0                      0                   0   
1356                             0                      0                   0   
1357                             0                      0                   0   
1358                             0                      0                   0   
1359                             0                      0                   0   

      7th Heaven  8 Mile  A Beautiful Mind  A Boy and His Dog  ...  \
0              0       0                 0                  0  ...   
1              0       0                 0                  0  ...   
2              0       0                 0                  0  ...   
3              0       0                 0                  0  ...   
4              0       0                 0                  0  ...   
...          ...     ...               ...                ...  ...   
1355           0       0                 0                  0  ...   
1356           0       0                 0                  0  ...   
1357           0       0                 0                  0  ...   
1358           0       0                 0                  0  ...   
1359           0       0                 0                  0  ...   

      Yesterday, Today and Tomorrow  You Can't Take It with You  \
0                                 0                           0   
1                                 0                           0   
2                                 0                           0   
3                                 0                           0   
4                                 0                           0   
...                             ...                         ...   
1355                              0                           0   
1356                              0                           0   
1357                              1                           0   
1358                              0                           1   
1359                              0                           0   

      You Don't Have to Die  You Light Up My Life  Young at Heart  Z  \
0                         0                     0               0  0   
1                         0                     0               0  0   
2                         0                     0               0  0   
3                         0                     0               0  0   
4                         0                     0               0  0   
...                     ...                   ...             ... ..   
1355                      0                     0               0  0   
1356                      0                     0               0  0   
1357                      0                     0               0  0   
1358              

In [54]:
 from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3)

In [55]:
x_train,x_test,y_train,y_test

(      12 Years a Slave  1917  20 Feet from Stardom  \
 161                  0     0                     0   
 964                  0     0                     0   
 975                  0     0                     0   
 1024                 0     0                     0   
 1014                 0     0                     0   
 ...                ...   ...                   ...   
 912                  0     0                     0   
 1266                 0     0                     0   
 1109                 0     0                     0   
 1125                 0     0                     0   
 1090                 0     0                     0   
 
       20,000 Leagues Under the Sea  2001: A Space Odyssey  7 Faces of Dr. Lao  \
 161                              0                      0                   0   
 964                              0                      0                   0   
 975                              0                      0                   0   
 1024     

In [59]:
from sklearn.ensemble import RandomForestClassifier
c = RandomForestClassifier()
c.fit(x_train, y_train)
y_pred = c.predict(x_test)
y_pred

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  4,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

In [61]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[  0   9   0   0   0   0   0   0   0   0   0]
 [  0 292   0   0   0   0   0   0   0   0   1]
 [  0  40   0   0   1   0   0   0   0   0   0]
 [  0  31   0   0   0   0   0   0   0   0   0]
 [  0  11   0   0   0   0   0   0   0   0   0]
 [  0   9   0   0   0   0   0   0   0   0   0]
 [  0   5   0   0   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]]


0.7156862745098039

In [62]:
from sklearn.ensemble import RandomForestClassifier
c = RandomForestClassifier(n_estimators=7,criterion='entropy',random_state=0)
c.fit(x_train, y_train)
y_pred = c.predict(x_test)
y_pred
accuracy_score(y_test,y_pred)

0.7156862745098039